export const PAGE_CONTENT = {
    REACTION_TEST: {
        TITLE: "Reaction Test",
        SUBTITLE: "Click or Press Space when ready",
        WAIT_FOR_GREEN: "Wait for Green",
        WAIT: "WAIT",
        CLICK: "CLICK!",
        TOO_EARLY: "TOO EARLY!",
        TRY_AGAIN: "Click to try again",
        HISTORY: "History:",
        MILLISECONDS: "ms",
    },

    F1_LIGHTS: {
        TITLE: "F1 Start Lights",
        DESCRIPTION: "React when all lights go out",
        WAIT: "WAIT...",
        GO: "GO!",
        FALSE_START: "FALSE START!",
        REACTION_TIME: "Reaction Time",
    },

    DECISION_TEST: {
        TITLE: "Decision Making",
        DESCRIPTION: "Press the correct key for each color",
        INSTRUCTIONS: "Q = Red, W = Blue, O = Green, P = Yellow",
        SCORE: "Score",
        ACCURACY: "Accuracy",
        CORRECT: "Correct!",
        WRONG: "Wrong!",
        FINISH: "Test Complete",
    },

    SEQUENCE_MEMORY: {
        TITLE: "Sequence Memory",
        DESCRIPTION: "Memorize and repeat the pattern",
        WATCH: "Watch the sequence...",
        YOUR_TURN: "YOUR TURN",
        CORRECT: "Correct!",
        WRONG: "Game Over",
        LEVEL: "Level",
        SEQUENCE_LENGTH: "Sequence Length",
    },

    MULTIPLAYER: {
        ENTER_NAME: "ENTER YOUR NAME",
        NAME_PLACEHOLDER: "Your racing name...",
        CONTINUE: "CONTINUE",
        MAIN_MENU: "MAIN MENU",
        CREATE_ROOM: "CREATE ROOM",
        JOIN_ROOM: "JOIN ROOM",
        ROOM_CODE: "ROOM CODE",
        ROOM_CODE_PLACEHOLDER: "Enter 5-letter code",
        JOIN: "JOIN",
        BACK: "BACK",
        WAITING_FOR_PLAYERS: "WAITING FOR PLAYERS...",
        ROOM_ID: "ROOM ID",
        PLAYERS: "PLAYERS",
        GAME_MODE: "GAME MODE",
        REACTION: "Reaction",
        F1_START: "F1 Start",
        SEQUENCE: "Sequence",
        DECISION: "Decision",
        READY: "READY",
        NOT_READY: "NOT READY",
        START_RACE: "START RACE",
        HOST: "HOST",
        WAITING_FOR_OPPONENT: "WAITING FOR OPPONENT...",
        WAITING_FOR_READY: "WAITING FOR READY...",
        WAITING_FOR_OTHERS: "WAITING FOR OTHERS",
        RACE_CHAT: "RACE CHAT",
        TYPE_MESSAGE: "Type a message...",
        SEND: "Send",
        NO_MESSAGES: "No communications yet...",
        FINISH_RACE: "FINISH RACE",
    },

    VICTORY: {
        RACE_COMPLETE: "RACE COMPLETE!",
        FINAL_RESULTS: "FINAL RESULTS",
        WINNER: "WINNER",
        POSITION: "Position",
        SCORE: "Score",
        REMATCH: "REMATCH",
        LEAVE: "LEAVE",
        FIRST_PLACE: "1ST",
        SECOND_PLACE: "2ND",
        THIRD_PLACE: "3RD",
    },

    PROFILE: {
        TITLE: "DRIVER",
        TITLE_HIGHLIGHT: "PROFILE",
        SELECT_AVATAR: "Select Avatar",
        CALLSIGN: "Callsign",
        CALLSIGN_PLACEHOLDER: "Enter your callsign...",
        REGION_TEAM: "Region / Team",
        REGION_PLACEHOLDER: "Enter 3-letter code (e.g., USA)",
        SAVE_PROFILE: "SAVE PROFILE",
        SAVING: "Saving...",
    },

    LEADERBOARD: {
        TITLE: "GLOBAL",
        TITLE_HIGHLIGHT: "LEADERBOARD",
        WORLDWIDE_RANKINGS: "WORLDWIDE RANKINGS",
        RANK: "Rank",
        DRIVER: "Driver",
        SCORE: "Score",
        LEVEL: "Level",
        VIEW_FULL: "VIEW FULL LEADERBOARD",
        TOP_DRIVERS: "TOP DRIVERS",
        YOUR_RANK: "Your Rank",
        PODIUM: "PODIUM",
    },

    DASHBOARD: {
        WELCOME: "Welcome back",
        YOUR_STATS: "Your Stats",
        GAMES_PLAYED: "Games Played",
        BEST_REACTION: "Best Reaction",
        LEVEL: "Level",
        GLOBAL_RANK: "Global Rank",
        QUICK_START: "QUICK START",
        DAILY_CHALLENGE: "Daily Challenge",
        COMPLETE_CHALLENGE: "Complete the challenge to earn bonus XP",
        START_CHALLENGE: "START CHALLENGE",
    },

    COMMON: {
        LOADING: "Loading...",
        ERROR: "Error",
        SUCCESS: "Success!",
        CANCEL: "Cancel",
        CONFIRM: "Confirm",
        CLOSE: "Close",
        SAVE: "Save",
        RESET: "Reset",
        PLAY: "Play",
        PAUSE: "Pause",
        STOP: "Stop",
        RETRY: "Retry",
        NEXT: "Next",
        PREVIOUS: "Previous",
    },
} as const;

export const TOAST_MESSAGES = {
    PROFILE_SAVED: "Profile saved successfully!",
    PROFILE_SAVE_ERROR: "Failed to save profile",
    SCORE_SAVED: "Score saved!",
    SCORE_SAVE_ERROR: "Failed to save score",
    ROOM_CREATED: "Room created successfully!",
    ROOM_JOINED: "Joined room successfully!",
    ROOM_JOIN_ERROR: "Failed to join room",
    ROOM_FULL: "Room is full",
    INVALID_ROOM_CODE: "Invalid room code",
    CONNECTION_ERROR: "Connection error. Please try again.",
    NETWORK_ERROR: "Network error. Check your connection.",
    GENERIC_ERROR: "Something went wrong. Please try again.",
} as const;

export const VALIDATION_MESSAGES = {
    NAME_REQUIRED: "Please enter your name",
    NAME_TOO_SHORT: "Name must be at least 2 characters",
    NAME_TOO_LONG: "Name must be less than 20 characters",
    ROOM_CODE_REQUIRED: "Please enter a room code",
    ROOM_CODE_INVALID: "Room code must be 5 characters",
    INVALID_INPUT: "Invalid input",
} as const;
